// strict mode is auto applied in that ide now by default if its not available use code {use strict;}
//alert(2+3)-->it is howing eror in node but not show in browser
console.log(3
    
    +3
)//here inside functions spaces are automaticallyu removed
//varoious datatypes
//number--used till 2 to power 53
//big int
//string
//boolean
//null
//undefined
//symbol---used to s how uniqueness
console.log(typeof "jatin rana")
console.log(typeof null)---//limitation
console.log(typeof undefined)